# Name of your blog
name: Praveen's blog

# Short description
description: This is my blog that is built by generating json files from markdown

# Your name
author: Praveen Kumar

# Your email 
author_email: m@praveen.xyz

# The directory for category index pages
category_dir: categories/

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain.
url: https://pkp.io

# Destination url
destination: _site/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
# Unfortunately .json exention is not supported by jekyll :(
permalink: /:year/:title/

# How many articles do you wish to appear on the front page:
#paginate: 5

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [package.json, node_modules]
